// 定义初始状态
const state = {
  returnUrl: '',
  phoneNumber: '--',
  bizToken: '',
  userInfo: null,
  serviceProtocolURL: '',
  popup: {
    isShow: false,
    show: false,
    type: 'alert',
    title: '',
    content: '',
    doOk: null,
    doCancel: null,
    okText: '确定',
    cancelText: '取消',
    duration: 1000,
  },
  prdList: {
    data: [],
    hasData: false,
  },
  productDetail: {},
  productPage: {
    initStatus: true,
    active: '1',
    rateStatus: 0,
    amountStatus: 0,
    totalAmountShow: false,
    timeStatus: false,
    selected: -1,
    isShowNewer: true,
  },
  secondPrdList: {
    pageNum: 1,
    productLimit: -1,
    pageSize: 10,
    data: [],
  },
  myAssets: {
    inviteActivityURL: 'https://promotion.hdfax.com/snow/invitation',
    assetsHomeInfo: {
      totalAssets: '0.00',
      totalBalance: '0.00',
      currentAssets: '0.00',
      currentTotalProfit: '0.00',
      fixedAssets: '0.00',
      fixedTotalProfit: '0.00',
      fundAssets: '0.00',
      fundTotalProfit: '0.00',
      estimatedFixedProfit: '0.00',
      zeroCurrentAssetsHint: '恒存金 灵活理财',
      zeroFixedAssetsHint: '多种产品 安全稳定',
      zeroFundAssetsHint: '申购费率 全场4折',
    },
    useableCouponCount: '0',
  },
  personSetting: {
    certificatedLevel: 3,
    portraitUrl: 'https://mobile.hdfax.com/assets/image/user/defaultPortrait.5f48ac02.png',
    phoneNumber: '--',
    realName: '--',
    bankCardNumber: '*******************',
    bankCardName: '--',
    hasPaymentPwd: 1,
    isRealName: 1,
    isBindBankCard: 1,
    riskScore: 55,
    riskLevel: 'R4',
    riskLevelDesc: '进取型',
    memberNo: '8a8181bd536aeee10153744e4bf301af',
    isRookie: 0,
  },
  myCouponList: {},
};

export default state;
